[theme]
# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#919e8b"  # green

# Background color for the main container.
backgroundColor = "#94A684"  # sepia yellow

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor = "#ebd2b9"  # wheat  "#d7ab82" # yellow <-- not enough contrast

# Font color for the page.
textColor = "#6e7074"  # grey

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans serif"

# Additional theme configurations
page_title = "Calories Burnt Prediction"
page_icon = ":chart_with_upwards_trend:"
initial_sidebar_state = "expanded"


# Additional configurations
buttonColor = "#AEC3AE"  # light blue
highlightBackgroundColor = "#fdae61"  # orange
headerColor = "#2c3e50"  # dark blue

[deprecation]
showPyplotGlobalUse = false